# All the path are relative to the project path passed with the --project option.
# Ex : /home/denis/official/ms-resource
# jobcontrol run --server eureka-peer-1-dev --port 20000  --profile ms-resource-dev  --project /home/denis/official/ms-resource --file ms-resource.toml

[App]
    bin="${PROJECT}/target/ms-resource-*.jar"
	cmd="java -Dserver.port=${PORT} -Dspring.profiles.active=${PROFILE} -jar  ${bin} "

[App.Status]
	# TODO find a way to make this url generic
    url="http://${SERVER}:${PORT}/actuator/health"
    keyword="UP"